// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.6.0
// source: 1.proto

package example

import (
	context "context"
	reflect "reflect"
	sync "sync"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 发送请求
type SendAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 发送的参数字段
	// 参数类型 参数名 标识号(不可重复)
	Address *string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"` // 要请求的地址
	Method  *string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`   // 请求方式
}

func (x *SendAddress) Reset() {
	*x = SendAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file__1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAddress) ProtoMessage() {}

func (x *SendAddress) ProtoReflect() protoreflect.Message {
	mi := &file__1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAddress.ProtoReflect.Descriptor instead.
func (*SendAddress) Descriptor() ([]byte, []int) {
	return file__1_proto_rawDescGZIP(), []int{0}
}

func (x *SendAddress) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *SendAddress) GetMethod() string {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return ""
}

// 返回响应
type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 接收的参数字段
	// 参数类型 参数名 标识号
	HttpCode *int32  `protobuf:"varint,1,opt,name=httpCode" json:"httpCode,omitempty"` // http状态码
	Response *string `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`  // 返回体
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file__1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file__1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file__1_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetHttpCode() int32 {
	if x != nil && x.HttpCode != nil {
		return *x.HttpCode
	}
	return 0
}

func (x *GetResponse) GetResponse() string {
	if x != nil && x.Response != nil {
		return *x.Response
	}
	return ""
}

var File__1_proto protoreflect.FileDescriptor

var file__1_proto_rawDesc = []byte{
	0x0a, 0x07, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x65, 0x6e,
	0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x45, 0x0a, 0x0b, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x74, 0x74,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x68, 0x74, 0x74,
	0x70, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xde, 0x01, 0x0a, 0x08, 0x47, 0x6f, 0x53, 0x70, 0x69, 0x64, 0x65, 0x72, 0x12, 0x31,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x30, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x1a, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x33, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x31, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x12, 0x33, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x12, 0x0c, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x1a, 0x0c, 0x2e, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x35, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x33, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x1a, 0x0c, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x74, 0x65, 0x73, 0x74,
}

var (
	file__1_proto_rawDescOnce sync.Once
	file__1_proto_rawDescData = file__1_proto_rawDesc
)

func file__1_proto_rawDescGZIP() []byte {
	file__1_proto_rawDescOnce.Do(func() {
		file__1_proto_rawDescData = protoimpl.X.CompressGZIP(file__1_proto_rawDescData)
	})
	return file__1_proto_rawDescData
}

var file__1_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file__1_proto_goTypes = []interface{}{
	(*SendAddress)(nil), // 0: SendAddress
	(*GetResponse)(nil), // 1: GetResponse
}
var file__1_proto_depIdxs = []int32{
	0, // 0: GoSpider.GetAddressResponse0:input_type -> SendAddress
	0, // 1: GoSpider.GetAddressResponse1:input_type -> SendAddress
	0, // 2: GoSpider.GetAddressResponse2:input_type -> SendAddress
	0, // 3: GoSpider.GetAddressResponse3:input_type -> SendAddress
	1, // 4: GoSpider.GetAddressResponse0:output_type -> GetResponse
	1, // 5: GoSpider.GetAddressResponse1:output_type -> GetResponse
	1, // 6: GoSpider.GetAddressResponse2:output_type -> GetResponse
	1, // 7: GoSpider.GetAddressResponse3:output_type -> GetResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file__1_proto_init() }
func file__1_proto_init() {
	if File__1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file__1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file__1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file__1_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file__1_proto_goTypes,
		DependencyIndexes: file__1_proto_depIdxs,
		MessageInfos:      file__1_proto_msgTypes,
	}.Build()
	File__1_proto = out.File
	file__1_proto_rawDesc = nil
	file__1_proto_goTypes = nil
	file__1_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GoSpiderClient is the client API for GoSpider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoSpiderClient interface {
	// rpc请求 请求的函数 (发送请求参数) returns (返回响应的参数)
	GetAddressResponse0(ctx context.Context, in *SendAddress, opts ...grpc.CallOption) (*GetResponse, error)
	//rpc请求 客户端流式
	GetAddressResponse1(ctx context.Context, opts ...grpc.CallOption) (GoSpider_GetAddressResponse1Client, error)
	//rpc请求 服务端流式
	GetAddressResponse2(ctx context.Context, in *SendAddress, opts ...grpc.CallOption) (GoSpider_GetAddressResponse2Client, error)
	//rpc请求 服务端客户端双流
	GetAddressResponse3(ctx context.Context, opts ...grpc.CallOption) (GoSpider_GetAddressResponse3Client, error)
}

type goSpiderClient struct {
	cc grpc.ClientConnInterface
}

func NewGoSpiderClient(cc grpc.ClientConnInterface) GoSpiderClient {
	return &goSpiderClient{cc}
}

func (c *goSpiderClient) GetAddressResponse0(ctx context.Context, in *SendAddress, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/GoSpider/GetAddressResponse0", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goSpiderClient) GetAddressResponse1(ctx context.Context, opts ...grpc.CallOption) (GoSpider_GetAddressResponse1Client, error) {
	stream, err := c.cc.NewStream(ctx, &_GoSpider_serviceDesc.Streams[0], "/GoSpider/GetAddressResponse1", opts...)
	if err != nil {
		return nil, err
	}
	x := &goSpiderGetAddressResponse1Client{stream}
	return x, nil
}

type GoSpider_GetAddressResponse1Client interface {
	Send(*SendAddress) error
	CloseAndRecv() (*GetResponse, error)
	grpc.ClientStream
}

type goSpiderGetAddressResponse1Client struct {
	grpc.ClientStream
}

func (x *goSpiderGetAddressResponse1Client) Send(m *SendAddress) error {
	return x.ClientStream.SendMsg(m)
}

func (x *goSpiderGetAddressResponse1Client) CloseAndRecv() (*GetResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goSpiderClient) GetAddressResponse2(ctx context.Context, in *SendAddress, opts ...grpc.CallOption) (GoSpider_GetAddressResponse2Client, error) {
	stream, err := c.cc.NewStream(ctx, &_GoSpider_serviceDesc.Streams[1], "/GoSpider/GetAddressResponse2", opts...)
	if err != nil {
		return nil, err
	}
	x := &goSpiderGetAddressResponse2Client{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GoSpider_GetAddressResponse2Client interface {
	Recv() (*GetResponse, error)
	grpc.ClientStream
}

type goSpiderGetAddressResponse2Client struct {
	grpc.ClientStream
}

func (x *goSpiderGetAddressResponse2Client) Recv() (*GetResponse, error) {
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *goSpiderClient) GetAddressResponse3(ctx context.Context, opts ...grpc.CallOption) (GoSpider_GetAddressResponse3Client, error) {
	stream, err := c.cc.NewStream(ctx, &_GoSpider_serviceDesc.Streams[2], "/GoSpider/GetAddressResponse3", opts...)
	if err != nil {
		return nil, err
	}
	x := &goSpiderGetAddressResponse3Client{stream}
	return x, nil
}

type GoSpider_GetAddressResponse3Client interface {
	Send(*SendAddress) error
	Recv() (*GetResponse, error)
	grpc.ClientStream
}

type goSpiderGetAddressResponse3Client struct {
	grpc.ClientStream
}

func (x *goSpiderGetAddressResponse3Client) Send(m *SendAddress) error {
	return x.ClientStream.SendMsg(m)
}

func (x *goSpiderGetAddressResponse3Client) Recv() (*GetResponse, error) {
	m := new(GetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GoSpiderServer is the server API for GoSpider service.
type GoSpiderServer interface {
	// rpc请求 请求的函数 (发送请求参数) returns (返回响应的参数)
	GetAddressResponse0(context.Context, *SendAddress) (*GetResponse, error)
	//rpc请求 客户端流式
	GetAddressResponse1(GoSpider_GetAddressResponse1Server) error
	//rpc请求 服务端流式
	GetAddressResponse2(*SendAddress, GoSpider_GetAddressResponse2Server) error
	//rpc请求 服务端客户端双流
	GetAddressResponse3(GoSpider_GetAddressResponse3Server) error
}

// UnimplementedGoSpiderServer can be embedded to have forward compatible implementations.
type UnimplementedGoSpiderServer struct {
}

func (*UnimplementedGoSpiderServer) GetAddressResponse0(context.Context, *SendAddress) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAddressResponse0 not implemented")
}
func (*UnimplementedGoSpiderServer) GetAddressResponse1(GoSpider_GetAddressResponse1Server) error {
	return status.Errorf(codes.Unimplemented, "method GetAddressResponse1 not implemented")
}
func (*UnimplementedGoSpiderServer) GetAddressResponse2(*SendAddress, GoSpider_GetAddressResponse2Server) error {
	return status.Errorf(codes.Unimplemented, "method GetAddressResponse2 not implemented")
}
func (*UnimplementedGoSpiderServer) GetAddressResponse3(GoSpider_GetAddressResponse3Server) error {
	return status.Errorf(codes.Unimplemented, "method GetAddressResponse3 not implemented")
}

func RegisterGoSpiderServer(s *grpc.Server, srv GoSpiderServer) {
	s.RegisterService(&_GoSpider_serviceDesc, srv)
}

func _GoSpider_GetAddressResponse0_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoSpiderServer).GetAddressResponse0(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GoSpider/GetAddressResponse0",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoSpiderServer).GetAddressResponse0(ctx, req.(*SendAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoSpider_GetAddressResponse1_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoSpiderServer).GetAddressResponse1(&goSpiderGetAddressResponse1Server{stream})
}

type GoSpider_GetAddressResponse1Server interface {
	SendAndClose(*GetResponse) error
	Recv() (*SendAddress, error)
	grpc.ServerStream
}

type goSpiderGetAddressResponse1Server struct {
	grpc.ServerStream
}

func (x *goSpiderGetAddressResponse1Server) SendAndClose(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *goSpiderGetAddressResponse1Server) Recv() (*SendAddress, error) {
	m := new(SendAddress)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GoSpider_GetAddressResponse2_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SendAddress)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GoSpiderServer).GetAddressResponse2(m, &goSpiderGetAddressResponse2Server{stream})
}

type GoSpider_GetAddressResponse2Server interface {
	Send(*GetResponse) error
	grpc.ServerStream
}

type goSpiderGetAddressResponse2Server struct {
	grpc.ServerStream
}

func (x *goSpiderGetAddressResponse2Server) Send(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GoSpider_GetAddressResponse3_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GoSpiderServer).GetAddressResponse3(&goSpiderGetAddressResponse3Server{stream})
}

type GoSpider_GetAddressResponse3Server interface {
	Send(*GetResponse) error
	Recv() (*SendAddress, error)
	grpc.ServerStream
}

type goSpiderGetAddressResponse3Server struct {
	grpc.ServerStream
}

func (x *goSpiderGetAddressResponse3Server) Send(m *GetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *goSpiderGetAddressResponse3Server) Recv() (*SendAddress, error) {
	m := new(SendAddress)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GoSpider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GoSpider",
	HandlerType: (*GoSpiderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAddressResponse0",
			Handler:    _GoSpider_GetAddressResponse0_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAddressResponse1",
			Handler:       _GoSpider_GetAddressResponse1_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetAddressResponse2",
			Handler:       _GoSpider_GetAddressResponse2_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAddressResponse3",
			Handler:       _GoSpider_GetAddressResponse3_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "1.proto",
}
